In [18]:
import pandas as pd
import plotly.express as px
import plotly.io as pio

pio.templates.default = None
from mainnet_launch.autopool_diagnostics.returns_before_expenses import (
    fetch_nav_and_shares_and_factors_that_impact_nav_per_share,
)
from mainnet_launch.constants import AUTO_LRT, BASE_ETH


df = fetch_nav_and_shares_and_factors_that_impact_nav_per_share(AUTO_LRT)

2024-12-03 15:57:41.954 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-03 15:57:41.955 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-03 15:57:41.956 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-03 15:57:41.958 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-03 15:57:41.958 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.


In [19]:
import numpy as np
actual_shares = df["actual_shares"].values
new_shares_from_streaming_fees = df["new_shares_from_streaming_fees"].values
shares_less_extra_shares = actual_shares - new_shares_from_streaming_fees

assert np.all(shares_less_extra_shares <= actual_shares)
shares_less_extra_shares[-3:], actual_shares[-3:]

(array([3252.7523539 , 3234.67236268, 3235.17415042]),
 array([3256.58855509, 3238.50856387, 3239.01035161]))

In [21]:
# nav is not touched = 
nav = df["actual_nav"].values

actual_nav_per_share = nav / actual_shares
adjusted_nav_per_share = nav / shares_less_extra_shares

actual_nav_per_share[-3:], adjusted_nav_per_share[-3:]
# if we remove our fees at every point the nav per share should be higher
assert np.all(actual_nav_per_share <= adjusted_nav_per_share)
actual_nav_per_share[-3:], adjusted_nav_per_share[-3:]

(array([1.00535992, 1.0054954 , 1.00576182]),
 array([1.00654561, 1.00668788, 1.00695443]))

In [ ]:
# if we remove the shares minted to fees
# then the count of fees should less

# nav per share is nav / share



nav100/ 100, 

In [58]:
# nav per share increase by .1  

# when its at 1 

1.1/1

1.1

In [60]:
(2.1-2) / 2

0.050000000000000044

In [61]:
(1.1-1) / 1

0.10000000000000009

In [59]:
2.1/1

2.1

In [57]:
px.line(df['additional_nav_if_price_return_was_0'])

In [55]:
px.line(df['actual_nav'])

In [41]:
df2 = pd.DataFrame()
df2.index = df.index
df2['actual_shares'] = actual_shares
df2['shares_less_extra_shares'] = shares_less_extra_shares
df2['nav'] = nav

df2['actual_nav_per_share'] = actual_nav_per_share
df2['adjusted_nav_per_share'] = adjusted_nav_per_share

In [42]:
px.line(df2[['adjusted_nav_per_share', 'actual_nav_per_share']])

In [ ]:
# see if there is another way to do this


In [43]:
px.line(df2[['adjusted_nav_per_share', 'actual_nav_per_share']].diff())

In [44]:
px.line(df2[['actual_shares', 'shares_less_extra_shares']])

In [45]:
px.line(df2[['actual_shares', 'shares_less_extra_shares']].diff())

In [46]:
px.line(df2['actual_shares'].diff() - df2['shares_less_extra_shares'].diff())

In [47]:
real_shares = df["actual_shares"].values
new_shares_from_streaming_fees = df["new_shares_from_streaming_fees"].values

shares_less_extra_shares = real_shares - reaL_extra_shares

df["adjusted_nav"] = df["actual_nav"].copy()
df["adjusted_shares"] = df["actual_shares"] - df["new_shares_from_streaming_fees"]
assert (df["adjusted_shares"] <= df["actual_shares"]).all()


df["adjusted_nav_per_share"] = df["actual_nav"] / df["adjusted_shares"]
df["actual_nav_per_share"] = df["actual_nav"] / df["actual_shares"]


px.line(df[["adjusted_nav_per_share", "actual_nav_per_share"]].diff())

In [48]:
px.line(df["adjusted_nav_per_share"].diff() - df["actual_nav_per_share"].diff())

In [49]:
df["adjusted_nav"] = df["actual_nav"].copy()
df["adjusted_shares"] = df["actual_shares"] - df["new_shares_from_streaming_fees"]

assert (df["adjusted_shares"] <= df["actual_shares"]).all()
df["adjusted_nav_per_share"] = df["actual_nav"] / df["adjusted_shares"]
df["actual_nav_per_share"] = df["actual_nav"] / df["actual_shares"]
df = df.round(2)
# at every point adjusted_nav_per_share ought to be less than actual_nav_per_share

px.line(df[["adjusted_nav_per_share", "actual_nav_per_share"]].diff().round(2))
# px.line(df[["adjusted_nav_per_share", "actual_nav_per_share"]].diff())

# I think this is a decimals error devision with two high precsion floating point numbers can leave some wiggle room

In [50]:
df

actual_nav  actual_shares  \
timestamp                                              
2024-09-15 00:00:00+00:00        0.41           0.41   
2024-09-16 00:00:00+00:00      313.85         313.85   
2024-09-17 00:00:00+00:00      619.24         619.32   
2024-09-18 00:00:00+00:00     1148.79        1149.22   
2024-09-19 00:00:00+00:00     1152.10        1152.76   
...                               ...            ...   
2024-11-29 00:00:00+00:00     3273.52        3256.48   
2024-11-30 00:00:00+00:00     3273.26        3256.48   
2024-12-01 00:00:00+00:00     3274.04        3256.59   
2024-12-02 00:00:00+00:00     3256.31        3238.51   
2024-12-03 00:00:00+00:00     3257.67        3239.01   

                           new_shares_from_periodic_fees  \
timestamp                                                  
2024-09-15 00:00:00+00:00                           0.00   
2024-09-16 00:00:00+00:00                           0.00   
2024-09-17 00:00:00+00:00                           0.00   
2024-09-18 00:00:00+00:00                           0.11   
2024-09-19 00:00:00+00:00                           0.13   
...                                                  ...   
2024-11-29 00:00:00+00:00                           2.90   
2024-11-30 00:00:00+00:00                           2.90   
2024-12-01 00:00:00+00:00                           2.90   
2024-12-02 00:00:00+00:00                           2.90   
2024-12-03 00:00:00+00:00                           2.90   

                           new_shares_from_streaming_fees  \
timestamp                                                   
2024-09-15 00:00:00+00:00                            0.00   
2024-09-16 00:00:00+00:00                            0.00   
2024-09-17 00:00:00+00:00                            0.01   
2024-09-18 00:00:00+00:00                            0.01   
2024-09-19 00:00:00+00:00                            0.01   
...                                                   ...   
2024-11-29 00:00:00+00:00                            3.84   
2024-11-30 00:00:00+00:00                            3.84   
2024-12-01 00:00:00+00:00                            3.84   
2024-12-02 00:00:00+00:00                            3.84   
2024-12-03 00:00:00+00:00                            3.84   

                           rebalance_from_idle_swap_cost  \
timestamp                                                  
2024-09-15 00:00:00+00:00                           0.00   
2024-09-16 00:00:00+00:00                           0.00   
2024-09-17 00:00:00+00:00                           0.05   
2024-09-18 00:00:00+00:00                           0.18   
2024-09-19 00:00:00+00:00                           0.44   
...                                                  ...   
2024-11-29 00:00:00+00:00                           2.18   
2024-11-30 00:00:00+00:00                           2.18   
2024-12-01 00:00:00+00:00                           2.18   
2024-12-02 00:00:00+00:00                           2.18   
2024-12-03 00:00:00+00:00                           2.18   

                           rebalance_not_idle_swap_cost  \
timestamp                                                 
2024-09-15 00:00:00+00:00                          0.00   
2024-09-16 00:00:00+00:00                          0.00   
2024-09-17 00:00:00+00:00                          0.00   
2024-09-18 00:00:00+00:00                          0.00   
2024-09-19 00:00:00+00:00                          0.00   
...                                                 ...   
2024-11-29 00:00:00+00:00                          0.53   
2024-11-30 00:00:00+00:00                          0.53   
2024-12-01 00:00:00+00:00                          0.54   
2024-12-02 00:00:00+00:00                          0.55   
2024-12-03 00:00:00+00:00                          0.56   

                           additional_nav_if_price_return_was_0  adjusted_nav  \
timestamp                                                                       
2024-09-15 0

In [51]:
px.line(df["new_shares_from_streaming_fees"].diff())

In [52]:
px.line(df["new_shares_from_streaming_fees"])  # note the diff is on the order of 10, 8 bps